version: '3'
services:
  app:
    image: node:22-alpine
    volumes:
      - .:/app
      - /app/node_modules
      - build:/app/build
    working_dir: /app
    command: sh -c "yarn install && yarn build"
  nginx:
    image: nginx:1.25.5-alpine
    volumes:
      - build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - app
volumes:
  build: